/**
 * Botox Bestie — curated static Q&A content.
 *
 * Botox Bestie is a feature/personality inside The Aesthetics Bible, not
 * the master brand (see CLAUDE.md). This is a mocked conversation surface
 * only — answers are curated and grounded in our local Bible content, not
 * generated by an LLM. Structured so a grounded assistant can later
 * retrieve/compose from the same underlying content without changing the
 * UI shape.
 *
 * Boundary: Bestie explains, compares, and helps users navigate
 * education. It never prescribes exact injection placement, dose, depth,
 * or diagnoses a face.
 */

export type BotoxBestieEntry = {
  id: string;
  question: string;
  answer: string;
};

export const botoxBestieEntries: BotoxBestieEntry[] = [
  {
    id: 'botox-vs-dysport',
    question: 'Botox or Dysport?',
    answer:
      'Both are neuromodulators in the same category, so they’re commonly explored for the same expression lines — the difference is more about formulation and spread than one being "better." A lot of it comes down to what your provider has the most experience injecting. Worth asking them directly which they’d recommend for your face and why.',
  },
  {
    id: 'quote-normal',
    question: 'Is this quote normal?',
    answer:
      'Pricing varies a lot by category, provider experience, and city — that’s exactly why we show typical cost ranges in The Bible for each treatment. If a quote is well outside that range in either direction, it’s worth asking what’s included (units, follow-up, touch-ups) before deciding.',
  },
  {
    id: 'consultation-questions',
    question: 'What should I ask at my consultation?',
    answer:
      'Three that go a long way: what results are realistic for my goals and by when, what downtime or aftercare should I plan for, and how many sessions are typically recommended. Every treatment page in The Bible has a starter list tailored to that category.',
  },
  {
    id: 'sofwave-buzz',
    question: 'What is everyone talking about with Sofwave?',
    answer:
      'Sofwave is an ultrasound-based device people explore for gentle lifting and firming without downtime — it’s often mentioned alongside Ultherapy as a lower-commitment alternative. Both build gradually over a few months rather than giving an instant result.',
  },
  {
    id: 'jowls-research',
    question: 'What should I research for jowls?',
    answer:
      'Jowls usually fall under skin laxity, so the categories worth reading up on are ultrasound treatments, RF, and threads — each with a different balance of downtime and cost. Take our quiz with "jawline" as your area and "loose or sagging skin" as your concern to see how they compare for you specifically.',
  },
];

export const botoxBestieDisclaimer =
  'Botox Bestie shares general education from The Bible — not a diagnosis, a prescription, or an exact plan for your face. A provider consultation is still the next step.';
